# Default values for LHDI QA environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true
env: qa
railsEnv: production
namespace: ves-developer-experience-qa
labels:
  app: ves-developer-experience
web:
  strategyType: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 1
  image:
    value: ghcr.io/department-of-veterans-affairs/ves-developer-experience
    tag: 0.54.0
    pullPolicy: IfNotPresent
  ports:
    - name: web
      containerPort: 3000
      servicePort: 3000
      protocol: TCP
  healthCheck:
    path: /ves-developer-experience/health
    port: 3000
    initialDelaySeconds: 20
    periodSeconds: 120
    successThreshold: 1
    failureThreshold: 4
# this will change for each environments value files
db:
  identifier: va-test-user-portal-qa
  name: va_test_user_portal_qa
# aws svc acct
serviceAccount:
  name: ves-developer-experience-svc-account-qa
# secrets configuration
# values for these will be pulled dynamically from vault once implemented
# current implementation is manual from an env file
secrets:
  ghcrSecretVersion: 3
  railsSecretVersion: 1
  awsDbSecretVersion: 4
  awsDbSecretva_test_user_portal_development:
    - name: database_password
    - name: postgres_password
    - name: database_host
    - name: database_user
  cacheSecretVersion: 1
  cacheSecret:
    - name: redis_host
    - name: redis_port
    - name: redis_app_data_url
    - name: redis_rails_cache_url
    - name: redis_sidekiq_url
svc:
  type: ClusterIP
  ports:
    - name: web
      containerPort: 3000
      servicePort: 3000
      protocol: TCP
virtualService:
  host: qa.lighthouse.va.gov
  gateway: istio-system/ldx-nonprod-1-qa-gateway
datadogEnv: qa
