name: Push the Docker image to AWS ECR Repo
on:
  push:
    branches:
      - test_branch
    tags:
      - ''
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get install -y python3-yaml

      - name: Read values.yml
        id: read_values
        run: |
          python3 -c "
          import yaml
          with open('values.yml','r') as file:
            data = yaml.safe_load(file)
            print(f'::set-output name=version::{data['version']}')
            print(f'::set-output name=version::{data['image_name']}')
          "

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get commit hash
        id: get-commit-hash
        run: echo "version=$(echo '0.0.1')" >> $GITHUB_OUTPUT

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "hello-world"
          IMAGE_TAG: ${{ steps.read_values.outputs.version }}
          #IMAGE_TAG: ${{ steps.get-commit-hash.outputs.version }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG