name: deploy-release-to-env

on:
  workflow_call:
    inputs:
      new_tag:
        description: 'Image tag'
        required: true
        type: string
      env:
        description: 'Environment'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'Image tag'
        required: true
        type: string
      env:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - qa

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ github.event.inputs.new_tag }}"
          echo "The environment is: ${{ github.event.inputs.env }}"

 