name: cron-test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Print Time
        id: set_version
        run: |
          pwd
          ls -la
          DAYS=-3
          VERSION=""
          while [[ $VERSION = "" ]]; do
            TAGDATE=`date --date="${DAYS} days ago" +"%Y-%m-%d"`
            git fetch --tags
            VERSION=`git tag -l --sort=-creatordate --format '%(creatordate:short)%09%(refname:strip=2)' | grep ${TAGDATE} | head -1 | awk '{print $2}'`
            DAYS=$((DAYS + 1))
          done
          echo "The next tag version will be: ${VERSION}"
          echo "version=$(echo $VERSION)" >> "$GITHUB_OUTPUT"
  here:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Print Time
        run: |
          echo "The next tag version will be: ${{ needs.test.outputs.version }}"
  prep:
    if: ${{ github.event_name == 'schedule'}}
    runs-on: ubuntu-latest
    name: Prep for Schedule
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Sets the Tag
        id: set_version
        run: |
          DAYS=-3
          VERSION=""
          while [[ $VERSION = "" ]]; do
            TAGDATE=`date --date="${DAYS} days ago" +"%Y-%m-%d"`
            git fetch --tags
            VERSION=`git tag -l --sort=-creatordate --format '%(creatordate:short)%09%(refname:strip=2)' | grep ${TAGDATE} | head -1 | awk '{print $2}'`
            DAYS=$((DAYS + 1))
          done
          echo "version=$(echo $VERSION)" >> "$GITHUB_OUTPUT"

  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: print
        run: |
          echo "The next tag version will be: ${{ needs.prep.outputs.version }}"
      - name: Deploy to QA
        uses: KarateTD/hello-world/.github/workflows/deploy-to-env.yml@main
        with:
          secerts: inherit
          env: 'qa'
          new_tag: '${{ needs.prep.outputs.version }}'

