name: cron-test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Print Time
        run: |
          pwd
          ls -la
          DAYS=-3
          VERSION=""
          while [[ $VERSION = "" ]]; do
            TAGDATE=`date --date="${DAYS} days ago" +"%Y-%m-%d"`
            git fetch --tags
            VERSION=`git tag -l --sort=-creatordate --format '%(creatordate:short)%09%(refname:strip=2)' | grep ${TAGDATE} | head -1 | awk '{print $2}'`
            DAYS=$((DAYS + 1))
          done
          echo "The next tag version will be: ${VERSION}"
  prep:
    if: ${{ github.event_name == 'schedule'}}
    runs-on: ubuntu-latest
    name: Prep for Schedule
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Sets the Tag
        id: set_version
        run: |
          DAYS=-3
          VERSION=""
          while [[ $VERSION = "" ]]; do
            TAGDATE=`date --date="${DAYS} days ago" +"%Y-%m-%d"`
            git fetch --tags
            VERSION=`git tag -l --sort=-creatordate --format '%(creatordate:short)%09%(refname:strip=2)' | grep ${TAGDATE} | head -1 | awk '{print $2}'`
            DAYS=$((DAYS + 1))
          done
          echo "::set-output name=version::${VERSION}"
  deploy-to-qa:
    needs: [prep]
    uses: KarateTD/hello-world/.github/workflows/deploy-to-env.yml@main
    secrets: inherit
    with:
      env: 'qa'
      new_tag: '${{ needs.prep.outputs.version }}'
